name: 'download_decrypt_archive'
description: ''
author: 'Paul Kelleher'
inputs:
  input:
    description: 'folder containing the terraform code to deploy'
    required: true
  encryption_key:
    description: 'Branch to select'
    required: true
  deployment_identifier:
    description: 'the name of the artifact to be stored/retrieved'
    required: true

runs:
  using: "composite"
  steps:
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow_conclusion: completed
        name: ${{ inputs.deployment_identifier }}.enc
        repo: ${{ github.repository }}
        check_artifacts:  true
        search_artifacts: true
        skip_unpack: true
        if_no_artifact_found: warn
    - name: unarchive
      run: |
        if [[ -f ${{ inputs.deployment_identifier }}.enc ]];
        then
          find . -name ${{ inputs.deployment_identifier }}.enc -exec openssl enc -d -aes-256-cbc -pass pass:"${{ inputs.encryption_key }}"  -in "{}" -out ${{ inputs.deployment_identifier }}.tgz \;
          find . -name ${{ inputs.deployment_identifier }}.tgz -exec tar -zxvf "{}" \;
        else
          echo "no artiufact to download"
        fi
      shell: bash
